### DISCUSSION TITLE
Cannot see series in post although available in the respective link

### DISCUSSION THREAD

**Discussion by joaohfrodrigues** [lxndrblz/anatole#546] [Q&A] [answered]
When adding posts to a series, I can see the respective link is created in series/, but the other series posts do not appear in the post itself.

Check the print screens below.

![image](https://github.com/user-attachments/assets/37cf93c9-e073-4868-b709-8335a3f0b527)

![image](https://github.com/user-attachments/assets/bdebb26b-d056-4447-959c-0681cff1215f)

In my hugo.toml i have:
``` toml
[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

```
In the post I have:

``` markdown
+++
author = "João Fialho Rodrigues"
title = "Italy 2024: Verona"
date = "2024-06-01"
description = "Visiting Verona, a beautiful city in the north of Italy"
tags = [
    "photography", "city", "italy", "verona"
]
series = 'italy'
+++
```
