### ISSUE TITLE
New Feature Query: Parameterized profile pic mask

### ISSUE THREAD

**Issue by cdichiara** [lxndrblz/anatole#118]
Personally, I think it adds to the theme:

![Screenshot 2021-01-12 23 44 47](https://user-images.githubusercontent.com/13836864/104407928-c792a600-5530-11eb-8db6-2bcb43bc8edc.png)

```toml
[params]
profilePicture = "images/profile.jpg"
profilePictureMask = "images/star.svg"
```

Just let me know, implementation is already done but hiding behind my other pull request because I messed up my master branch over here. I'll make some more sample masks to put into the theme.

Carmine
