### ISSUE TITLE
Query re: css pipeline tweaks...

### ISSUE THREAD

**Issue by cdichiara** [lxndrblz/anatole#119]
I'm wondering if you'd like to include Google font parameterization.

![Screenshot 2021-01-13 00 20 00](https://user-images.githubusercontent.com/13836864/104409945-5bff0780-5535-11eb-891b-a8d9d473f746.png)
![Screenshot 2021-01-13 00 21 29](https://user-images.githubusercontent.com/13836864/104409954-5e616180-5535-11eb-8301-031f6fd52b6d.png)

```toml
[params]
## Google fonts
googleFont = "Hachi Maru Pop"
```

Already complete, just unfortunately sitting behind the recaptcha pull request due to a messed up master branch on my side - sorry.
