### ISSUE TITLE
Profile page vertical alignment issue

### ISSUE THREAD

**Issue by chuk-yong** [lxndrblz/anatole#192]
Hi!  On the main page, the profile picture is centred but all the favicons are below and covered.  How do I move everything up?

<img width="958" alt="Screenshot 2021-05-03 084806" src="https://user-images.githubusercontent.com/18753521/116833582-aabbd480-abec-11eb-96ff-b6c7d9402098.png">

**Comment by lxndrblz** [comment]
@chuk-yong You would need to adjust the spacing by lowering the padding top of this CSS class:
```css
.sidebar .logo-title {
    text-align: center;
    padding-top: 240px;
    flex: 1;
}
```

Out of curiosity, on which kind of oddly shaped device did you take this screenshot?
