### ISSUE TITLE
GA 4 parameter does not work

### ISSUE THREAD

**Issue by ryan1-chang** [lxndrblz/anatole#228]
GA 4 parameter does not work
```toml
[params]
gtagId = "G-XXXXXXXXXX"
```

I added the following code to this file

```html
<!-- layouts/partials/head.html -->
<head>
  {{ if .Site.Params.gtagId }}
  {{ partial "google-analytics-gtag-async.html" . }}
  {{ end }}
  ...
</head>
```
