### ISSUE TITLE
Broken language selector style after update to v1.11.0

### ISSUE THREAD

**Issue by McPringle** [lxndrblz/anatole#384]
**Describe the bug**
After my update from v1.10.0 to v1.11.0 the language selector style is broken. It does not show a dropdown as expected. It is now shown as a (misaligned) list.

**To Reproduce**

1. Update theme to v1.11.0
2. Run `hugo server`

**Expected behavior**
The language selector should still be shown as a dropdown.

**Screenshots**
Screenshot with theme version 1.10.0:
![image](https://user-images.githubusercontent.com/1254039/193443985-df36739b-7c0e-4335-b11d-234b9dd5d776.png)
Screenshot with theme version 1.11.0:
![image](https://user-images.githubusercontent.com/1254039/193444007-c6d57b0c-ee5d-49ab-9ade-7f598103921b.png)

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome, Firefox
- Version of the Theme: 1.11.0
- Version of Hugo: v0.104.2-84cbe724983b4b6153fd39aae0888cbb89a56cda windows/amd64 BuildDate=2022-09-29T10:31:09Z

**Smartphone (please complete the following information):**
_No test from myself on a smartphone._

**Additional context**
I only added some CSS for the profile picture:

```css
img.sidebar__introduction-profileimage {
    filter: grayscale(100%);
}

img.sidebar__introduction-profileimage:hover {
    filter: grayscale(0);
}
```

That should not have any effect to the language selector.
