### ISSUE TITLE
In v1.11.0 social profile links are missing the "rel=me" attribute

### ISSUE THREAD

**Issue by McPringle** [lxndrblz/anatole#399]
**Describe the bug**
Until v1.10.0 social profile links had the "rel=me" attribute:
![image](https://user-images.githubusercontent.com/1254039/202851260-4aa3804a-94a3-471e-8d90-ba84be64eff8.png)

In v1.11.0 this attribute is missing:
![image](https://user-images.githubusercontent.com/1254039/202851308-aeb0b814-1ad7-499d-a82f-cb13d43217b5.png)

This attribute is important for verification, e.g. Mastodon.

**To Reproduce**

1. Render the website using v1.10.0: attribute is there
2. Render the same website using v1.11.0: attribute is missing

**Expected behavior**
I would expect the attribute "rel=me" to be there.

**Screenshots**
See description.

**Desktop**
- OS: all
- Browser: all
- Version of the Theme: v1.11.0
- Version of Hugo: hugo v0.106.0-e08ce30fe4779e7d8a8395d7021314b915648cb4 windows/amd64 BuildDate=2022-11-17T18:33:40Z VendorInfo=gohugoio

**Smartphone**
- Device: all
- OS: all
- Browser: all
- Version of the Theme: v1.11.0
- Version of Hugo: hugo v0.106.0-e08ce30fe4779e7d8a8395d7021314b915648cb4 windows/amd64 BuildDate=2022-11-17T18:33:40Z VendorInfo=gohugoio

**Additional context**
- One blog of me rendered with theme v1.10.0 (rel=me works): https://fihlon.swiss/en/
- One blog of me rendered with theme v1.11.0 (rel-me missing): https://keep-on-rolling.ch/en/
- No custom JavaScript.
- This is the only custom CSS on fihlon.swiss:
```css
img.sidebar__introduction-profileimage {
    filter: grayscale(100%);
}

img.sidebar__introduction-profileimage:hover {
    filter: grayscale(0);
}
```
- This is the only custom CSS on keep-on-rolling.ch:
```css
img.sidebar__introduction-profileimage {
    border-radius: 0;
}

body.theme--light img.sidebar__introduction-profileimage {
    background: url(/images/logo-black.png) no-repeat;
}

body.theme--dark img.sidebar__introduction-profileimage {
    background: url(/images/logo-white.png) no-repeat;
}
```
- Repository of my personal website using theme v1.10.0: https://github.com/McPringle/mcpringle.github.io
- Repository of my cycling blog using theme v1.11.0: https://github.com/keep-on-rolling/keep-on-rolling.github.io
