### ISSUE TITLE
Problem with icons not displaying

### ISSUE THREAD

**Issue by joe-mann** [lxndrblz/anatole#409]
**Describe the bug**
I'm trying to add the `file-user` icon to the sidebar, but it isn't displaying.

**To Reproduce**

Add the following to `config.toml` and go to the home page.

```toml
[[params.socialIcons]]
icon = "fas fa-file-user"
title = "Foo"
url = "/posts/"
```

**Expected behavior**

Expect the `file-user` icon to be present in the sidebar.

**Desktop (please complete the following information):**

- OS: Linux
- Browser Firefox
- v1.12.0
- `hugo v0.108.0+extended linux/amd64 BuildDate=unknown`

**Additional context**

Other icons, such as the social icons described [here](https://github.com/lxndrblz/anatole/wiki/1%EF%B8%8F%E2%83%A3-Essential-Steps#setting-up-the-social-icons-in-the-sidebar), display fine.
