### ISSUE TITLE
Previewing website from local directory fails to load CSS

### ISSUE THREAD

**Issue by Gregory-Gelfond** [lxndrblz/anatole#58]
When viewing my site using `hugo server -D` and loading `http://localhost:1313`, everything appears to work correctly. However, if I generate static webpages using `hugo -D`, and the attempt to open `public/index.html` in my browser, it appears that none of the CSS is loaded.

I have to admit that I'm new to using Hugo, the theme, and also web dev, so I'm assuming this is the best place to ask the question.

What follows is my `config.toml` which is basically a direct copy of the one you provided in the example site (although I may be missing something):

```toml
baseURL = "http://localhost:1313"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Random Thoughts"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
# disqusShortname = ""

# Google Analytics
# googleAnalytics = "UA-123-45"

[params]
title = "Random Thoughts"
author = "Gregory Gelfond"
description = "Computer scientist, philosopher, lifelong learner"
profilePicture = "images/hobbes.jpg"
keywords = ""
favicon = "favicons/"
customCss = []
customJs = []
mainSections = ["post"]
images = ["images/explorers.jpg"]

## Math settings
[params.math]
enable = true  # options: true, false.
use = "mathjax"  # options: "katex", "mathjax".

## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/Gregory-Gelfond"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:ggelfond@unomaha.edu"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"
```
