### ISSUE TITLE
Changing to a custom font 

### ISSUE THREAD

**Issue by ivangjxyz** [lxndrblz/anatole#87]
I get that you will probably dismiss this. This is too personal of an issue. But anyway, I wanted to ask, just in case. 

I've tried to copy what [the cupper theme guys do](https://github.com/zwbetz-gh/cupper-hugo-theme/tree/master/static/css/fonts) for having a **custom font**. 
I added the fonts to `static/fonts/` and then I did this in my `assets/css/custom.css` (+ all the other font styles): 
```
@font-face {
    font-family: 'Atkinson Hyperlegible';
    src: url('{{ "fonts/Atkinson-Hyperlegible-Bold-102a.woff2" | absURL }}') format('woff2'), url('{{ "fonts/Atkinson-Hyperlegible-Bold-102.woff" | absURL }}') format('woff');
    font-weight: bold;
    font-style: normal;

```
which technically parallels the cupper theme work... but when I do: 
```
body {
    color: var(--body-color);
    font-family: 'Atkinson Hyperlegible', normal;
    font-size: 15px;
    width: 100%;
    margin: 0 auto 30px auto;
    background-color: var(--bg-color);
}
```
it defaults to the browser's default font. 

Do you know any way to make it actually work?

**Comment by lxndrblz** [comment]
I was able to get it working:

![image](https://user-images.githubusercontent.com/12200062/97788251-92bcb700-1baf-11eb-998a-bbab66f1b192.png)

## Steps:
- Copy the fonts into a separate fonts directory inside of the css static folder
- Create a new custom css (fonts.css) in the main static css folder
- Link the new css in your config.toml
- Add a css which looks like this:

```css

@font-face {
    font-family: "Atkinson Hyperlegible";
    src: url("./fonts/Atkinson-Hyperlegible-Regular-102.woff") format('woff');
}

@font-face {
    font-family: "Atkinson Hyperlegible";
    src: url("./fonts/Atkinson-Hyperlegible-Bold-102.woff") format('woff');
    font-weight: bold;
}

@font-face {
    font-family: "Atkinson Hyperlegible";
    src: url("./fonts/Atkinson-Hyperlegible-BoldItalic-102.woff") format('woff');
    font-weight: bold;
    font-style: italic;
}

@font-face {
    font-family: "Atkinson Hyperlegible";
    src: url("./fonts/Atkinson-Hyperlegible-Italic-102.woff") format('woff');
    font-style: italic;
}

body {
    color: var(--body-color);
    font-family: 'Atkinson Hyperlegible', normal;
    font-size: 15px;
    width: 100%;
    margin: 0 auto 30px auto;
    background-color: var(--bg-color);
}
```
